---
sidebar: sidebar 
permalink: reference-log-in-to-instance.html 
keywords: log in, data sense, classification 
summary: A veces es posible que tengas que iniciar sesión en el sistema de clasificación de BlueXP para poder acceder a los archivos de registro o editar los archivos de configuración. 
---
= Inicia sesión en el sistema de clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A veces es posible que tengas que iniciar sesión en el sistema de clasificación de BlueXP para poder acceder a los archivos de registro o editar los archivos de configuración.

Cuando la clasificación de BlueXP está instalada en un equipo Linux en las instalaciones o en un equipo Linux implementado en la nube, puedes acceder al archivo de configuración y al script directamente.

Cuando se pone en marcha la clasificación de BlueXP en la nube, necesitas SSH para la instancia de clasificación de BlueXP. Debe SSH al sistema introduciendo el usuario y la contraseña, o usando la clave SSH que ha proporcionado durante la instalación de BlueXP Connector. El comando SSH es:

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>
* <path_to_the_ssh_key> = ubicación de claves de autenticación ssh
* <machine_user>.:
+
** Para AWS: Utilice <ec2-user>
** Para Azure: Utilice el usuario creado para la instancia de BlueXP
** Para GCP: Utilice el usuario creado para la instancia de BlueXP


* <datasense_ip> = dirección IP de la instancia de la máquina virtual


Tenga en cuenta que deberá modificar las reglas entrantes del grupo de seguridad para acceder al sistema en la nube. Para obtener más información, consulte:

* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-aws.html["Reglas del grupo de seguridad en AWS"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Reglas de grupos de seguridad en Azure"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-gcp.html["Reglas de firewall en Google Cloud"^]

