---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: El software de clasificación de BlueXP debe ejecutarse en un host que cumpla con los requisitos específicos del sistema operativo, los requisitos de RAM, los requisitos de software, etc. Al poner en marcha la clasificación de BlueXP en el cloud, le recomendamos que utilice un sistema con las características «grandes» para disfrutar de todas las funciones. 
---
= Tipos de instancia de clasificación de BlueXP admitidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software de clasificación de BlueXP debe ejecutarse en un host que cumpla con los requisitos específicos del sistema operativo, los requisitos de RAM, los requisitos de software, etc. Al poner en marcha la clasificación de BlueXP en el cloud, le recomendamos que utilice un sistema con las características «grandes» para disfrutar de todas las funciones.

Puedes poner en marcha la clasificación de BlueXP en un sistema con menos CPU y menos RAM, pero existen algunas limitaciones al usar estos sistemas menos potentes. link:concept-cloud-compliance.html#using-a-smaller-instance-type["Obtenga información sobre estas limitaciones"^].

En las siguientes tablas, si el sistema marcado como «predeterminado» no está disponible en la región donde instalas la clasificación de BlueXP, se implementará el siguiente sistema de la tabla.



== Tipos de instancia de AWS

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://["m6i.4xgrande"^] (por defecto) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 


| Mediano | 8 CPU, 32 GB de RAM, 200 GIB de SSD | https://["m6i.2xgrande"^] (por defecto) m6a.2xlarge m5a.2xlarge m5.2xlarge m4.2xlarge 


| Pequeño | 8 CPU, 16 GB de RAM, 100 GIB de SSD | https://["cera.2xlarge"^] (predeterminado) c5a.2xgrande c5.2xgrande c4.2xgrande 
|===


== Tipos de instancia de Azure

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://["Standard_D16s_v3"^] (predeterminado) 
|===


== Tipos de instancia de GCP

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://["n2-estándar-16"^] (predeterminado) n2d-standard-16 n1-standard-16 
|===