---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: data sense, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'El software de detección de datos debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de software, etc. A la hora de poner en marcha Data Sense en el cloud, recomendamos utilizar un sistema con las "grandes" características para disponer de todas las funciones.' 
---
= Tipos de instancia de Data Sense admitidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software de detección de datos debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de software, etc. A la hora de poner en marcha Data Sense en el cloud, recomendamos utilizar un sistema con las "grandes" características para disponer de todas las funciones.

Puede implementar la detección de datos en un sistema con menos CPU y menos RAM, pero hay algunas limitaciones al utilizar estos sistemas menos potentes. link:concept-cloud-compliance.html#using-a-smaller-instance-type["Obtenga información sobre estas limitaciones"^].

En las tablas siguientes, si el sistema marcado como "predeterminado" no está disponible en la región donde está instalando Data Sense, se desplegará el siguiente sistema de la tabla.



== Tipos de instancia de AWS

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xgrande"^] (por defecto) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 


| Mediano | 8 CPU, 32 GB de RAM, 200 GIB de SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.2xgrande"^] (por defecto) m6a.2xlarge m5a.2xlarge m5.2xlarge m4.2xlarge 


| Pequeño | 8 CPU, 16 GB de RAM, 100 GIB de SSD | https://aws.amazon.com/ec2/instance-types/c6a/["cera.2xlarge"^] (predeterminado) c5a.2xgrande c5.2xgrande c4.2xgrande 
|===


== Tipos de instancia de Azure

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^] (predeterminado) 
|===


== Tipos de instancia de GCP

[cols="20,30,25"]
|===
| Tamaño del sistema | Especificaciones | Tipo de instancia 


| Grande | 16 CPU, 64 GB de RAM, 500 GIB de SSD | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-estándar-16"^] (predeterminado) n2d-standard-16 n1-standard-16 
|===