---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Hay muchos tipos de datos privados que la clasificación de BlueXP puede identificar en tus volúmenes, bloques de Amazon S3, bases de datos, carpetas de OneDrive, cuentas de SharePoint, etc. Y cuentas de Google Drive. 
---
= Categorías de datos privados en clasificación BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay muchos tipos de datos privados que la clasificación de BlueXP puede identificar en tus volúmenes y bases de datos.

La clasificación de BlueXP identifica dos tipos de datos personales:

* *Información de identificación personal (PII)*
* *Información personal sensible (SPII)*



TIP: Si necesita una clasificación BlueXP  para identificar otros tipos de datos privados, como números de identificación nacionales adicionales o identificadores de atención médica, póngase en contacto con su administrador de cuenta.



== Tipos de datos personales

Los datos personales, o información personal identificable_ (PII), que se encuentran en los archivos pueden ser datos personales generales o identificadores nacionales. La tercera columna de la siguiente tabla identifica si la clasificación de BlueXP lo utiliza link:task-controlling-private-data.html#view-files-that-contain-personal-data["validación de proximidad"^] validar los resultados del identificador.

Los idiomas en los que se pueden reconocer estos elementos se identifican en la tabla.

[cols="13,37,10,8,8,8,8,8"]
|===
| Tipo | Identificador | ¿validación de proximidad? | Inglés | Alemán | Español | Francés | Japonés 


.6+| Generales | Número de tarjeta de crédito | No | ✓ | ✓ | ✓ |  | ✓ 


| Datos sujetos | No | ✓ | ✓ | ✓ |  |  


| Dirección de correo electrónico | No | ✓ | ✓ | ✓ |  | ✓ 


| Número IBAN (número internacional de cuenta bancaria) | No | ✓ | ✓ | ✓ |  | ✓ 


| Dirección IP | No | ✓ | ✓ | ✓ |  | ✓ 


| Contraseña | Sí | ✓ | ✓ | ✓ |  | ✓ 


.57+| Identificadores nacionales | Australian TFN (número de archivo fiscal) | Sí | ✓ | ✓ | ✓ |  |  


| Licencia Australian Driver's License | Sí | ✓ | ✓ | ✓ |  |  


| Número de Medicare de Australia | Sí | ✓ | ✓ | ✓ |  |  


| Número de pasaporte Australiano | Sí | ✓ | ✓ | ✓ |  |  


| SSN austríaco | Sí | ✓ | ✓ | ✓ |  |  


| ID belga (Numero Nacional) | Sí | ✓ | ✓ | ✓ |  |  


| Número de tarjeta de identidad de Botswana (Omang) | Sí | ✓ | ✓ | ✓ |  |  


| Número de pasaporte de Botswana | Sí | ✓ | ✓ | ✓ |  |  


| ID brasileño (CPF) | Sí | ✓ | ✓ | ✓ |  |  


| Pasaporte Británico | Sí | ✓ | ✓ | ✓ |  |  


| ID búlgaro (UCN) | Sí | ✓ | ✓ | ✓ |  |  


| Croata ID (OIB) | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal de Chipre (TIC) | Sí | ✓ | ✓ | ✓ |  |  


| ID checo/eslovaco | Sí | ✓ | ✓ | ✓ |  |  


| ID danés (CPR) | Sí | ✓ | ✓ | ✓ |  |  


| Dutch ID (BSN) | Sí | ✓ | ✓ | ✓ |  |  


| Identificación Estonia | Sí | ✓ | ✓ | ✓ |  |  


| Finlandés ID (HETU) | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir francesa | Sí | ✓ | ✓ | ✓ | ✓ |  


| ID francés | Sí | ✓ | ✓ | ✓ | ✓ |  


| INSEE | Sí | ✓ | ✓ | ✓ | ✓ |  


| Número de la Seguridad Social Francesa | Sí | ✓ | ✓ | ✓ | ✓ |  


| Número de identificación fiscal francés (SPI) | Sí | ✓ | ✓ | ✓ | ✓ |  


| Identificación alemana (Personalausweisnummer) | Sí | ✓ | ✓ | ✓ |  |  


| Alemania - ID Interno para Transferencias Bancarias | Sí | ✓ | ✓ | ✓ |  |  


| Número de Seguro Social Alemán (Sozialversicherungsnummer) | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal alemán (Steuerliche Identifikationsnummer) | Sí | ✓ | ✓ | ✓ |  |  


| ID griego | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal húngaro | Sí | ✓ | ✓ | ✓ |  |  


| Irish ID (PPS) | Sí | ✓ | ✓ | ✓ |  |  


| Documento de identidad israelí | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal italiana | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación personal japonés (personal y corporativo) | Sí | ✓ | ✓ | ✓ |  | ✓ 


| ID letón | Sí | ✓ | ✓ | ✓ |  |  


| ID lituano | Sí | ✓ | ✓ | ✓ |  |  


| ID de Luxemburgo | Sí | ✓ | ✓ | ✓ |  |  


| Identificación maltesa | Sí | ✓ | ✓ | ✓ |  |  


| Número del Servicio Nacional de Salud (NHS) | Sí | ✓ | ✓ | ✓ |  |  


| Cuenta bancaria de Nueva Zelanda | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir de Nueva Zelanda | Sí | ✓ | ✓ | ✓ |  |  


| Número IRD de Nueva Zelanda (ID fiscal) | Sí | ✓ | ✓ | ✓ |  |  


| Número NHI (Índice Nacional de Salud) de Nueva Zelandia | Sí | ✓ | ✓ | ✓ |  |  


| Número de pasaporte de Nueva Zelanda | Sí | ✓ | ✓ | ✓ |  |  


| Identificación polaca (PESEL) | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal (NIF) en portugués | Sí | ✓ | ✓ | ✓ |  |  


| Rumano ID (CNP) | Sí | ✓ | ✓ | ✓ |  |  


| Tarjeta de identidad de registro nacional de Singapur (NRIC) | Sí | ✓ | ✓ | ✓ |  |  


| ID esloveno (EMSO) | Sí | ✓ | ✓ | ✓ |  |  


| ID sudafricano | Sí | ✓ | ✓ | ✓ |  |  


| Número de identificación fiscal en español | Sí | ✓ | ✓ | ✓ |  |  


| ID sueco | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir de Texas | Sí | ✓ | ✓ | ✓ |  |  


| REINO UNIDO ID (NINO) | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir de Estados Unidos California | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir de Estados Unidos Indiana | Sí | ✓ | ✓ | ✓ |  |  


| Licencia de conducir de los Estados Unidos de Nueva York | Sí | ✓ | ✓ | ✓ |  |  


| Número de Seguro Social de Estados Unidos (SSN) | Sí | ✓ | ✓ | ✓ |  |  
|===


== Tipos de datos personales confidenciales

La clasificación de BlueXP puede encontrar la siguiente información personal confidencial (SPII) en archivos.

Los elementos de esta categoría sólo se pueden reconocer en inglés en este momento.

* *Referencia de Procedimientos Penales*: Datos relativos a las condenas y delitos penales de una persona física.
* *Referencia étnica*: Datos relativos al origen racial o étnico de una persona física.
* *Referencia de salud*: Datos relativos a la salud de una persona física.
* *Códigos Médicos ICD-9-CM*: Códigos utilizados en la industria médica y de la salud.
* *Códigos Médicos ICD-10-CM*: Códigos utilizados en la industria médica y de la salud.
* *Referencia de creencias filosóficas*: Datos relativos a las creencias filosóficas de una persona natural.
* *Referencia de opiniones políticas*: Datos relativos a las opiniones políticas de una persona física.
* *Referencia de creencias religiosas*: Datos relativos a las creencias religiosas de una persona natural.
* *Vida sexual u Orientación Referencia*: Datos relativos a la vida sexual u orientación sexual de una persona natural.




== Tipos de categorías

La clasificación de BlueXP categoriza los datos de la siguiente manera.

La mayoría de estas categorías pueden ser reconocidas en inglés, alemán y español.

[cols="25,25,15,15,15"]
|===
| Categoría | Tipo | Inglés | Alemán | Español 


.4+| Finanzas | Hojas de balance | ✓ | ✓ | ✓ 


| Órdenes de compra | ✓ | ✓ | ✓ 


| Facturas | ✓ | ✓ | ✓ 


| Informes trimestrales | ✓ | ✓ | ✓ 


.6+| RR. HH | Comprobaciones de fondo | ✓ |  | ✓ 


| Planes de compensación | ✓ | ✓ | ✓ 


| Contratos de empleados | ✓ |  | ✓ 


| Revisiones de empleados | ✓ |  | ✓ 


| Salud | ✓ |  | ✓ 


| Se reanudará | ✓ | ✓ | ✓ 


.2+| Legal | NDAS | ✓ | ✓ | ✓ 


| Contratos con el proveedor y el cliente | ✓ | ✓ | ✓ 


.2+| Marketing | Campañas | ✓ | ✓ | ✓ 


| Conferencias | ✓ | ✓ | ✓ 


| Operaciones | Informes de auditoría | ✓ | ✓ | ✓ 


| Ventas | Pedidos de ventas | ✓ | ✓ |  


.4+| Servicios | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| CERDA | ✓ | ✓ | ✓ 


| Entrenamiento | ✓ | ✓ | ✓ 


| Soporte técnico | Quejas y boletos | ✓ | ✓ | ✓ 
|===
Los siguientes metadatos también se categorizan y se identifican en los mismos idiomas compatibles:

* Datos de aplicaciones
* Archivos de archivo
* Audio
* Rutas de navegación de la clasificación de BlueXP
Datos de aplicaciones de negocio
* Archivos CAD
* Codificación
* Dañado
* Archivos de base de datos e índice
* Archivos de diseño
* Datos de aplicación de correo electrónico
* Cifrado (archivos con una puntuación de entropía alta)
* Ejecutables
* Datos de aplicaciones financieras
* Datos de aplicación de salud
* Imágenes
* Registros
* Documentos varios
* Presentaciones diversas
* Hojas de cálculo varias
* Varios "desconocidos"
* Archivos protegidos con contraseña
* Datos estructurados
* Vídeos
* Archivos de byte cero




== Tipos de archivos

La clasificación de BlueXP analiza todos los archivos para buscar información de categorías y metadatos y muestra todos los tipos de archivos en la sección Tipos de archivos de la consola.

Pero cuando la clasificación de BlueXP detecta información personal identificable (PII) o cuando realiza una búsqueda DSAR, solo son compatibles los siguientes formatos de archivo:

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



== Precisión de la información encontrada

NetApp no puede garantizar la precisión del 100 % de los datos personales y los datos personales confidenciales que identifica la clasificación de BlueXP. Siempre debe validar la información revisando los datos.

Según nuestras pruebas, la tabla siguiente muestra la precisión de la información que encuentra la clasificación de BlueXP. La dividiremos por _precision_ y _RECALL_:

Precisión:: La probabilidad de que lo que encuentra la clasificación de BlueXP se haya identificado correctamente. Por ejemplo, una tasa de precisión del 90% para los datos personales significa que 9 de cada 10 archivos identificados como que contienen información personal contienen realmente información personal. 1 de cada 10 archivos sería un falso positivo.
Recuperar:: La probabilidad de que la clasificación de BlueXP encuentre lo que debería. Por ejemplo, una tasa de recuperación del 70 % de los datos personales significa que la clasificación de BlueXP puede identificar 7 de cada 10 archivos que contengan realmente información personal en tu organización. La clasificación de BlueXP faltaría el 30 % de los datos y no aparecerá en el panel.


Constantemente estamos mejorando la precisión de nuestros resultados. Esas mejoras estarán disponibles de forma automática en futuras versiones de clasificación de BlueXP.

[cols="25,20,20"]
|===
| Tipo | Precisión | Recuperar 


| Datos personales - General | 90%-95% | 60%-80% 


| Datos personales: Identificadores de país | 30%-60% | 40%-60% 


| Datos personales confidenciales | 80%-95% | 20%-30% 


| Categorías | 90%-97% | 60%-80% 
|===