---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: Actividades de gestión de registros de clasificación de BlueXP que se han realizado en archivos de todos los entornos de trabajo y fuentes de datos que está analizando la clasificación de BlueXP. La clasificación de BlueXP también registra las actividades al implementar la instancia de clasificación de BlueXP. 
---
= Audita el historial de acciones de clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Actividades de gestión de registros de clasificación de BlueXP que se han realizado en archivos de todos los entornos de trabajo y fuentes de datos que está analizando la clasificación de BlueXP. La clasificación de BlueXP también registra las actividades al implementar la instancia de clasificación de BlueXP.

Puede ver el contenido de los archivos de registro de auditoría de clasificación de BlueXP o descargarlos, para ver qué cambios se han producido en los archivos y cuándo. Por ejemplo, puede ver qué solicitud se emitió, la hora de la solicitud y detalles como la ubicación de origen en caso de que se haya eliminado un archivo o la ubicación de origen y destino en caso de que se haya movido un archivo.



== Contenido del archivo de registro

Cada línea del registro de auditoría contiene información con el siguiente formato:

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* Fecha y hora: Marca de hora completa del evento
* Estado: INFORMACIÓN, AVISO
* Tipo de acción (eliminar, copiar, mover, crear política, actualizar política, Volver a analizar archivos, descargar informes JSON, etc.)
* Nombre de archivo (si la acción es relevante para un archivo)
* Detalles de la acción - lo que se hizo: Depende de la acción
+
** Nombre de la política
** Para mover: Origen y destino
** Para copia - origen y destino
** Para etiqueta: Nombre de etiqueta
** Para asignar a: Nombre de usuario
** Para alerta de correo electrónico: Dirección/cuenta de correo electrónico




Por ejemplo, las siguientes líneas del archivo de registro muestran una operación de copia correcta y una operación de copia con errores.

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== Ubicaciones de archivos de registro

Los archivos de registro de auditoría de gestión están ubicados en la máquina de clasificación de BlueXP en lo siguiente: `/opt/netapp/audit_logs/`

Los archivos de registro de auditoría de instalación se escriben en `/opt/netapp/install_logs/`

Cada archivo de registro puede tener un tamaño máximo de 10 MB. Cuando se alcanza ese límite, se inicia un nuevo archivo de registro. Los archivos de registro se denominan "DataSense_audit.log", "DataSense_audit.log.1", "DataSense_audit.log.2", etc. Un máximo de 100 archivos de registro se retienen en el sistema - los archivos de registro antiguos se eliminan automáticamente una vez alcanzado el máximo.



== Acceder a los archivos de registro

Tendrás que iniciar sesión en el sistema de clasificación de BlueXP para acceder a los archivos de registro. Descubra cómo link:reference-log-in-to-instance.html["Inicia sesión en el sistema de clasificación de BlueXP"] Dependiendo de si instaló manualmente el software en una máquina Linux o si implementó la instancia en la nube.
