---
sidebar: sidebar 
permalink: task-exclude-scan-paths.html 
keywords: exclude scans, folders, directories 
summary: Si desea que la clasificación de BlueXP excluya los datos de análisis que residen en determinados directorios de orígenes de datos, puede añadir estos nombres de directorio a un archivo de configuración. Después de aplicar este cambio, el motor de clasificación de BlueXP excluirá el análisis de datos en esos directorios. 
---
= Excluye directorios específicos de las exploraciones de clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si desea que la clasificación de BlueXP excluya los datos de análisis que residen en determinados directorios de orígenes de datos, puede añadir estos nombres de directorio a un archivo de configuración. Después de aplicar este cambio, el motor de clasificación de BlueXP excluirá el análisis de datos en esos directorios.

Tenga en cuenta que la clasificación de BlueXP está configurada de forma predeterminada para excluir los datos de copias Snapshot de volumen de análisis porque el contenido es idéntico al contenido del volumen.

Esta funcionalidad está disponible en la clasificación de BlueXP versión 1,29 y posteriores (a partir de marzo de 2024).



== Orígenes de datos compatibles

Se admite la exclusión de directorios específicos de los análisis de clasificación de BlueXP para los recursos compartidos NFS y CIFS en las siguientes fuentes de datos:

* ONTAP en las instalaciones
* Cloud Volumes ONTAP
* Amazon FSX para ONTAP de NetApp
* Azure NetApp Files
* Recursos generales para recursos compartidos de archivos




== Defina los directorios que se excluirán de la exploración

Para poder excluir los directorios del análisis de clasificación, debe iniciar sesión en el sistema de clasificación de BlueXP para poder editar un archivo de configuración y ejecutar un script. Descubra cómo link:reference-log-in-to-instance.html["Inicia sesión en el sistema de clasificación de BlueXP"] Dependiendo de si instaló manualmente el software en una máquina Linux o si implementó la instancia en la nube.

[NOTE]
====
* Puedes excluir un máximo de 50 rutas de directorio por sistema de clasificación de BlueXP.
* La exclusión de las rutas de acceso de directorio puede afectar a los tiempos de exploración.


====
.Pasos
. En el sistema de clasificación de BlueXP, vaya a «/opt/netapp/config/custom_configuration» y abra el archivo `data_provider.yaml`.
. En la sección “data_providers”, bajo la línea “exclude:”, introduzca las rutas de acceso del directorio que desea excluir. Por ejemplo:
+
....
exclude:
- "folder1"
- "folder2"
....
+
No cambie nada más en este archivo.

. Guarde los cambios en el archivo.
. Vaya a «/opt/netapp/Datasense/tools/customer_configuration/data_providers» y ejecute el siguiente script:
+
 update_data_providers_from_config_file.sh
+
Este comando confirma los directorios que se excluirán de la exploración en el motor de clasificación.



.Resultado
Todos los escaneos posteriores de sus datos excluirán el escaneo de esos directorios especificados.

Puede agregar, editar o eliminar elementos de la lista de exclusión mediante estos mismos pasos. La lista de exclusión revisada se actualizará después de ejecutar el script para confirmar los cambios.



== Ejemplos

.Configuración 1:
Cada carpeta que contenga “folder1” en cualquier lugar del nombre será excluida de todas las fuentes de datos.

....
data_providers:
   exclude:
   - "folder1"
....
.Resultados esperados para las rutas que se excluirán:
* /CVO1/folder1
* /CVO1/folder1name
* /CVO1/folder10
* /CVO1/*folder1
* /CVO1/+folder1name
* /CVO1/notfolder10
* /CVO22/folder1
* /CVO22/folder1name
* /CVO22/folder10


.Ejemplos de rutas que no se excluirán:
* /CVO1/*carpeta
* /CVO1/nombre de carpeta
* /CVO22/*folder20


.Configuración 2:
Cada carpeta que contenga “*folder1” solo al inicio del nombre será excluida.

....
data_providers:
   exclude:
   - "\\*folder1"
....
.Resultados esperados para las rutas que se excluirán:
* /CVO/*folder1
* /CVO/*folder1name
* /CVO/*folder10


.Ejemplos de rutas que no se excluirán:
* CVO/folder1
* CVO/folder1name
* /CVO/no*folder10


.Configuración 3:
Todas las carpetas del origen de datos “CVO22” que contengan “folder1” en cualquier lugar del nombre serán excluidas.

....
data_providers:
   exclude:
   - "CVO22/folder1"
....
.Resultados esperados para las rutas que se excluirán:
* /CVO22/folder1
* /CVO22/folder1name
* /CVO22/folder10


.Ejemplos de rutas que no se excluirán:
* /CVO1/folder1
* /CVO1/folder1name
* /CVO1/folder10




== Escape de caracteres especiales en los nombres de carpetas

Si tiene un nombre de carpeta que contiene uno de los siguientes caracteres especiales y desea excluir los datos de esa carpeta de ser escaneados, deberá utilizar la secuencia de escape \\ antes del nombre de la carpeta.

 ., +, *, ?, ^, $, (, ), [, ], {, }, |
Por ejemplo:

Ruta de acceso en origen: `/project/*not_to_scan`

Sintaxis en el archivo de exclusión: `"\\*not_to_scan"`



== Ver la lista de exclusión actual

Es posible para el contenido del `data_provider.yaml` el archivo de configuración debe ser diferente al que se ha confirmado después de ejecutar el `update_data_providers_from_config_file.sh` guión. Para ver la lista actual de directorios que ha excluido del análisis de clasificación de BlueXP, ejecute el siguiente comando en «/opt/netapp/Datasense/tools/customer_configuration/data_providers»:

 get_data_providers_configuration.sh