---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, cloud compliance access, compliance, on-premises, linux, test linux system 
summary: Antes de instalar Data Sense manualmente en un host Linux, puede ejecutar un script en el host para verificar que todos los requisitos previos estén en su lugar para la instalación de Data Sense. Puede ejecutar este script en un host Linux de su red o en un host Linux de la nube. El host puede conectarse a Internet, o el host puede residir en un sitio que no tenga acceso a Internet. 
---
= Compruebe que su host Linux esté listo para instalar Data Sense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar Data Sense manualmente en un host Linux, puede ejecutar un script en el host para verificar que todos los requisitos previos estén en su lugar para la instalación de Data Sense. Puede ejecutar este script en un host Linux de su red o en un host Linux de la nube. El anfitrión puede ser conectado a Internet, o el anfitrión puede residir en un sitio que no tiene acceso a Internet (un "sitio oscuro").

También hay una secuencia de comandos de prueba de requisito previo que forma parte del script de instalación de Data Sense. El script descrito aquí está diseñado específicamente para los usuarios que desean verificar el host Linux independientemente de ejecutar el script de instalación de Data Sense.



== Primeros pasos

Realizará las siguientes tareas.

. Opcional. Instale un conector BlueXP si aún no tiene uno instalado. Puede ejecutar la secuencia de comandos de prueba sin tener un conector instalado, pero la secuencia de comandos comprueba la conectividad entre el conector y la máquina host de detección de datos, por lo que se recomienda tener un conector.
. Prepare el equipo host y compruebe que cumple todos los requisitos.
. Habilite el acceso saliente a Internet desde el equipo host de Data Sense.
. Verifique que todos los puertos necesarios estén activados en todos los sistemas.
. Descargue y ejecute el script de prueba de requisito previo.




== Cree un conector

Se necesita un conector BlueXP para poder instalar y utilizar Data Sense. No obstante, puede ejecutar el script Prerequisites sin un conector.

Puede hacerlo https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-on-prem.html["Instale el conector en las instalaciones"^] En un host Linux de su red o en un host Linux del cloud. Algunos usuarios que planean instalar Data Sense on-prem también pueden optar por instalar el conector on-prem.

Para crear un conector en su entorno de proveedor de cloud, consulte https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html["Creación de un conector en AWS"^], https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-azure.html["Creación de un conector en Azure"^], o. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-google.html["Creación de un conector en GCP"^].

Necesitará la dirección IP o el nombre de host del sistema Connector cuando ejecute el script Prerequisites. Tendrá esta información si instaló el conector en sus instalaciones. Si el conector está implementado en la nube, puede encontrar esta información desde la consola BlueXP: Haga clic en el icono Ayuda, seleccione *Soporte* y haga clic en *conector BlueXP*.



== Verifique los requisitos del host

El software de detección de datos debe ejecutarse en un host que cumpla con requisitos específicos del sistema operativo, requisitos de RAM, requisitos de software, etc.

* No se admite la detección de datos en un host que se comparte con otras aplicaciones; el host debe ser un host dedicado.


* Al crear el sistema host en sus instalaciones, puede elegir entre tres tamaños de sistema en función del tamaño del conjunto de datos que desee realizar un análisis de detección de datos.
+
[cols="18,18,26,30"]
|===
| Tamaño del sistema | CPU | RAM (la memoria de intercambio debe estar desactivada) | Disco 


| *Grande* | 16 CPU | 64 GB DE MEMORIA RAM | 500 GIB SSD en /, o - 100 GIB disponibles en /opt - 395 GIB disponibles en /var - 5 GIB en /tmp 


| *Media* | 8 CPU | 32 GB DE MEMORIA RAM | 200 GIB SSD en /, o - 50 GIB disponibles en /opt - 145 GIB disponibles en /var - 5 GIB en /tmp 


| *Pequeño* | 8 CPU | 16 GB DE MEMORIA RAM | 100 GIB SSD en /, o - 50 GIB disponibles en /opt - 45 GIB disponibles en /var - 5 GIB en /tmp 
|===
+
Tenga en cuenta que existen limitaciones al usar estos sistemas más pequeños. Consulte link:concept-cloud-compliance.html#using-a-smaller-instance-type["Con un tipo de instancia más pequeño"] para obtener más detalles.

* Al poner en marcha una instancia de cloud para su instalación de Data Sense, recomendamos un sistema que cumpla los requisitos del sistema "grandes" anteriores:
+
** *Tipo de instancia de AWS EC2*: Recomendamos "m6i.4xlarge". link:reference-instance-types.html#aws-instance-types["Consulte tipos de instancia de AWS adicionales"^].
** *Azure VM size*: Recomendamos "Standard_D16s_v3". link:reference-instance-types.html#azure-instance-types["Consulte tipos de instancia de Azure adicionales"^].
** *Máquina GCP tipo*: Recomendamos "n2-standard-16". link:reference-instance-types.html#gcp-instance-types["Consulte tipos de instancia de GCP adicionales"^].


* *Sistema operativo*: Red Hat Enterprise Linux o CentOS versiones 8.0 a 8.7
+
** CentOS Stream 8 también es compatible
** Se pueden utilizar las versiones 7.8 o 7.9, pero la versión de kernel de Linux debe ser 4.0 o posterior
** El sistema operativo debe ser capaz de instalar el motor del docker


* *Red Hat Subscription Management*: Un sistema Red Hat Enterprise Linux debe estar registrado con Red Hat Subscription Management. Si no está registrado, el sistema no puede acceder a los repositorios para actualizar el software de terceros necesario durante la instalación.
* *Software adicional*: Debe instalar el siguiente software en el host antes de instalar Data Sense:
+
** Docker Engine versión 19.3.1 o posterior. https://docs.docker.com/engine/install/["Ver las instrucciones de instalación"^].
** Python 3 versión 3.6 o posterior. https://www.python.org/downloads/["Ver las instrucciones de instalación"^].


* * Consideraciones de Firewalld*: Si usted está planeando utilizar `firewalld`, Le recomendamos que lo habilite antes de instalar Data Sense. Ejecute los siguientes comandos para configurar `firewalld` Para que sea compatible con Data Sense:
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Si tiene previsto utilizar hosts de detección de datos adicionales como nodos de escáner (en un modelo distribuido), agregue estas reglas al sistema principal en este momento:

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Si activa `firewalld` Después de instalar Data Sense, debe reiniciar docker.





== Active el acceso saliente a Internet desde Data Sense

El sentido de datos requiere acceso saliente a Internet. Si la red virtual o física utiliza un servidor proxy para el acceso a Internet, asegúrese de que la instancia de detección de datos tiene acceso saliente a Internet para contactar con los siguientes puntos finales.

CONSEJO:: Esta sección no es necesaria para los sistemas host instalados en sitios sin conexión a Internet.


[cols="43,57"]
|===
| Puntos finales | Específico 


| \https://api.bluexp.netapp.com | Comunicación con el servicio BlueXP, que incluye cuentas de NetApp. 


| \https://netapp-cloud-account.auth0.com \https://auth0.com | Comunicación con el sitio Web de BlueXP para la autenticación centralizada del usuario. 


| \https://support.compliance.api.bluexp.netapp.com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | Proporciona acceso a imágenes de software, manifiestos, plantillas y para enviar registros y métricas. 


| \https://support.compliance.api.bluexp.netapp.com/ | Permite a NetApp transmitir datos desde registros de auditoría. 


| \https://github.com/docker \https://download.docker.com \http://mirror.centos.org \http://mirrorlist.centos.org \http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm | Proporciona paquetes de requisitos previos para la instalación. 
|===


== Verifique que todos los puertos necesarios estén habilitados

Debe asegurarse de que todos los puertos necesarios estén abiertos para la comunicación entre el conector, detección de datos, Active Directory y sus orígenes de datos.

[cols="25,25,50"]
|===
| Tipo de conexión | Puertos | Descripción 


| Conector <> detección de datos | 8080 (TCP), 443 (TCP) y 80 | El firewall o las reglas de enrutamiento del conector deben permitir el tráfico entrante y saliente a través del puerto 443 hacia y desde la instancia de detección de datos. Asegúrese de que el puerto 8080 está abierto para que pueda ver el progreso de la instalación en BlueXP. 


| Conector <> clúster ONTAP (NAS) | 443 (TCP)  a| 
BlueXP detecta los clústeres de ONTAP mediante HTTPS. Si utiliza directivas de firewall personalizadas, el host del conector debe permitir el acceso HTTPS de salida a través del puerto 443. Si el conector está en la nube, todas las comunicaciones salientes se permiten mediante el firewall predefinido o las reglas de enrutamiento.

|===


== Ejecute el script de requisitos previos de detección de datos

Siga estos pasos para ejecutar la secuencia de comandos de requisitos previos de detección de datos.

.Lo que necesitará
* Compruebe que su sistema Linux cumple con el <<Verifique los requisitos del host,requisitos del host>>.
* Compruebe que el sistema tiene instalados los dos paquetes de software de requisitos previos (Docker Engine y Python 3).
* Asegúrese de tener privilegios de usuario raíz en el sistema Linux.


.Pasos
. Descargue el script de requisitos previos de detección de datos de https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Sitio de soporte de NetApp"^]. El archivo que debe seleccionar se denomina *test_datosense_prerrequisitos_<version>*.
. Copie el archivo en el host Linux que tiene previsto utilizar (mediante `scp` o algún otro método).
. Asigne permisos para ejecutar el script.
+
[source, cli]
----
chmod +x test_datasense_prerequisites_1_0
----
. Ejecute el script con el siguiente comando.
+
./test_datensense_prerrequisitos_1_0 &#8592;-darksite>
[source, cli]
----
Add the option "--darksite" only if you are running the script on a host that doesn't have internet access. Certain prerequisite tests are skipped when the host is not connected to the internet.
----
. La secuencia de comandos solicita la dirección IP del equipo host de Data Sense.
+
** Introduzca la dirección IP o el nombre de host.


. La secuencia de comandos le indica si tiene un conector BlueXP instalado.
+
** Introduzca *N* si no tiene un conector instalado.
** Introduzca *y* si tiene un conector instalado. A continuación, introduzca la dirección IP o el nombre de host del conector BlueXP para que la secuencia de comandos de prueba pueda probar esta conectividad.


. La secuencia de comandos ejecuta una variedad de pruebas en el sistema y muestra los resultados a medida que avanza. Cuando termine, escribe un registro de la sesión en un archivo.


.Resultado
Si todas las pruebas de requisitos previos se ejecutaron correctamente, puede instalar Data Sense en el host cuando esté listo.

Si se detectan problemas, se clasifican como "recomendado" o "requerido" para ser solucionados. Los problemas recomendados son normalmente elementos que harían que el análisis de detección de datos y la categorización de las tareas se ejecutarían más lentamente. No es necesario corregir estos elementos, pero es posible que desee abordarlos.

Si tiene algún problema "requerido", debe solucionar los problemas y volver a ejecutar el script de prueba de requisitos previos.
