---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, bluexp, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, ubuntu, rhel, dark site, bluexp 
summary: Antes de instalar manualmente la clasificación de BlueXP en un host Linux, puede ejecutar un script en el host para comprobar que haya todos los requisitos previos para instalar la clasificación de BlueXP. Puede ejecutar este script en un host Linux de su red o en un host Linux de la nube. El host puede conectarse a Internet, o el host puede residir en un sitio que no tenga acceso a Internet. 
---
= Compruebe que su host Linux esté listo para instalar la clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar manualmente la clasificación BlueXP  en un host Linux, puede ejecutar de manera opcional un script en el host para comprobar que estén establecidos todos los requisitos previos para instalar la clasificación BlueXP . Puede ejecutar este script en un host Linux de su red o en un host Linux de la nube. El host se puede conectar a Internet, o el host puede residir en un sitio que no tiene acceso a Internet (un _sitio oscuro_).

También hay un script de prueba de requisito previo que forma parte del script de instalación de clasificación de BlueXP. El script descrito aquí está específicamente diseñado para usuarios que quieren verificar el host Linux independientemente de ejecutar el script de instalación de la clasificación de BlueXP.



== Primeros pasos

Realizará las siguientes tareas.

. Opcionalmente, instale un conector BlueXP si aún no tiene uno instalado. Puede ejecutar el script de prueba sin tener instalado un Connector, pero el script comprueba la conectividad entre el Connector y el equipo host de clasificación de BlueXP, por lo que se recomienda tener un Connector.
. Prepare el equipo host y compruebe que cumple todos los requisitos.
. Habilita el acceso a Internet saliente desde el equipo host de clasificación de BlueXP.
. Verifique que todos los puertos necesarios estén activados en todos los sistemas.
. Descargue y ejecute el script de prueba de requisito previo.




== Cree un conector

Es necesario un conector BlueXP para poder instalar y utilizar la clasificación de BlueXP. No obstante, puede ejecutar el script Prerequisites sin un conector.

Puede hacerlo https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["Instale el conector en las instalaciones"^] En un host Linux de su red o en un host Linux del cloud. Algunos usuarios que planean instalar la clasificación de BlueXP en las instalaciones también pueden optar por instalar el conector en las instalaciones.

Para crear un conector en su entorno de proveedor de cloud, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Creación de un conector en AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Creación de un conector en Azure"^], o. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Creación de un conector en GCP"^].

Necesitará la dirección IP o el nombre de host del sistema Connector cuando ejecute el script Prerequisites. Tendrá esta información si instaló el conector en sus instalaciones. Si el conector está implementado en la nube, puede encontrar esta información desde la consola BlueXP: Haga clic en el icono Ayuda, seleccione *Soporte* y haga clic en *conector BlueXP*.



== Verifique los requisitos del host

El software de clasificación de BlueXP debe ejecutarse en un host que cumpla con los requisitos específicos del sistema operativo, los requisitos de RAM, los requisitos de software, etc.

* La clasificación de BlueXP no se admite en un host compartido con otras aplicaciones; el host debe ser un host dedicado.
* Al crear el sistema host en sus instalaciones, se puede elegir entre estos tamaños del sistema según el tamaño del conjunto de datos al que vaya a analizar la clasificación de BlueXP.
+
[cols="17,17,27,31"]
|===
| Tamaño del sistema | CPU | RAM (la memoria de intercambio debe estar desactivada) | Disco 


| * Extra grande* | 32 CPU | 128 GB DE MEMORIA RAM  a| 
** SSD de 1 TiB en / o 100 GiB disponible en /opt
** 895 GiB disponible en /var/lib/docker
** 5 GIB en /tmp
** *Para Podman, 5 GB en /tmp*
** *Para Podman, 30 GB en /var/tmp*




| *Grande* | 16 CPU | 64 GB DE MEMORIA RAM  a| 
** 500 GiB SSD en / o 100 GiB disponible en /opt
** 395 GiB disponible en /var/lib/docker, para Podman /var/lib/containers o para Podman /var/lib/containers
** 5 GIB en /tmp
** *Para Podman, 5 GB en /tmp*
** *Para Podman, 30 GB en /var/tmp*


|===
* A la hora de poner en marcha una instancia de computación en la nube para la instalación de tu clasificación de BlueXP, te recomendamos un sistema que cumpla los requisitos «grandes» del sistema anteriores:
+
** *Tipo de instancia de Amazon Elastic Compute Cloud (Amazon EC2)*: Recomendamos “m6i.4xlarge”. link:reference-instance-types.html#aws-instance-types["Consulte tipos de instancia de AWS adicionales"^].
** *Azure VM size*: Recomendamos "Standard_D16s_v3". link:reference-instance-types.html#azure-instance-types["Consulte tipos de instancia de Azure adicionales"^].
** *Máquina GCP tipo*: Recomendamos "n2-standard-16". link:reference-instance-types.html#gcp-instance-types["Consulte tipos de instancia de GCP adicionales"^].


* *Permisos de carpeta UNIX*: Se requieren los siguientes permisos mínimos de UNIX:
+
[cols="25,25"]
|===
| Carpeta | Permisos mínimos 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/docker | `rwx------` 


| /usr/lib/systemd/system | `rwxr-xr-x` 
|===
* *sistema operativo*:
+
** Los siguientes sistemas operativos requieren el uso del motor de contenedor Docker:
+
*** Red Hat Enterprise Linux versiones 7,8 y 7,9
*** Ubuntu 22,04 (requiere la versión de clasificación de BlueXP 1,23 o posterior)
*** Ubuntu 24,04 (requiere la versión de clasificación de BlueXP 1,23 o posterior)


** Los siguientes sistemas operativos requieren el uso del motor de contenedor Podman y requieren la versión de clasificación de BlueXP 1,30 o posterior:
+
*** Red Hat Enterprise Linux versiones 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 y 9,5


** Las extensiones vectoriales avanzadas (AVX) deben estar habilitadas en el sistema host.


* *Red Hat Subscription Management*: El host debe estar registrado en Red Hat Subscription Management. Si no está registrado, el sistema no puede acceder a los repositorios para actualizar el software de 3rd partes necesario durante la instalación.
* *Software adicional*: Debes instalar el siguiente software en el host antes de instalar la clasificación BlueXP:
+
** Dependiendo del sistema operativo que esté utilizando, deberá instalar uno de los motores de contenedores:
+
*** Docker Engine versión 19.3.1 o posterior. https://docs.docker.com/engine/install/["Ver las instrucciones de instalación"^].
*** Podman versión 4 o superior. Para instalar Podman, introduzca (`sudo yum install podman netavark -y`).






* Python versión 3,6 o superior. https://www.python.org/downloads/["Ver las instrucciones de instalación"^].
+
** *Consideraciones sobre NTP*: NetApp recomienda configurar el sistema de clasificación BlueXP para usar un servicio de Protocolo de hora de red (NTP). La hora debe sincronizarse entre el sistema de clasificación de BlueXP y el sistema BlueXP Connector.




* * Consideraciones de Firewalld*: Si usted está planeando utilizar `firewalld`, Te recomendamos que lo habilites antes de instalar la clasificación de BlueXP. Ejecute los siguientes comandos para configurar `firewalld` Para que sea compatible con la clasificación de BlueXP:
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Si tienes pensado usar otros hosts de clasificación de BlueXP como nodos de escáner (en un modelo distribuido), añade estas reglas a tu sistema principal en este momento:

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Tenga en cuenta que debe reiniciar Docker o Podman cada vez que habilite o actualice `firewalld` configuración.





== Habilita el acceso a Internet saliente desde la clasificación de BlueXP

La clasificación de BlueXP requiere acceso a Internet saliente. Si tu red física o virtual utiliza un servidor proxy para acceder a Internet, asegúrese de que la instancia de clasificación de BlueXP tenga acceso a Internet saliente para contactar con los siguientes extremos.


TIP: Esta sección no es necesaria para los sistemas host instalados en sitios sin conexión a Internet.

[cols="43,57"]
|===
| Puntos finales | Específico 


| \https://api.bluexp.netapp.com | Comunicación con el servicio BlueXP, que incluye cuentas de NetApp. 


| \https://netapp-cloud-account.auth0.com \https://auth0.com | Comunicación con el sitio Web de BlueXP para la autenticación centralizada del usuario. 


| \https://support.compliance.api.bluexp.netapp.com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | Proporciona acceso a imágenes de software, manifiestos, plantillas y para enviar registros y métricas. 


| \https://support.compliance.api.bluexp.netapp.com/ | Permite a NetApp transmitir datos desde registros de auditoría. 


| \https://github.com/docker \https://download.docker.com | Proporciona paquetes de requisitos previos para la instalación de Docker. 


| \http://packages.ubuntu.com/
\http://archive.ubuntu.com | Proporciona paquetes de requisitos previos para la instalación de Ubuntu. 
|===


== Verifique que todos los puertos necesarios estén habilitados

Debes asegurarte de que todos los puertos requeridos estén abiertos para la comunicación entre el conector, la clasificación de BlueXP, Active Directory y los orígenes de datos.

[cols="25,25,50"]
|===
| Tipo de conexión | Puertos | Descripción 


| Conector Clasificación de <> BlueXP | 8080 (TCP), 443 (TCP) y 80. 9000 | El firewall o las reglas de enrutamiento para Connector deben permitir el tráfico de entrada y salida a través del puerto 443 hacia y desde la instancia de clasificación de BlueXP. Asegúrese de que el puerto 8080 está abierto para que pueda ver el progreso de la instalación en BlueXP. Si se utiliza un firewall en el host Linux, se requiere el puerto 9000 para los procesos internos de un servidor Ubuntu. 


| Conector <> clúster ONTAP (NAS) | 443 (TCP)  a| 
BlueXP detecta los clústeres de ONTAP mediante HTTPS. Si utiliza directivas de firewall personalizadas, el host del conector debe permitir el acceso HTTPS de salida a través del puerto 443. Si el conector está en la nube, todas las comunicaciones salientes se permiten mediante el firewall predefinido o las reglas de enrutamiento.

|===


== Ejecuta el script Prerequisites de clasificación de BlueXP

Sigue estos pasos para ejecutar el script de requisitos previos de clasificación de BlueXP.

https://youtu.be/5ONowfPWkFs?si=QLGUw8mqPrz9qs4B["Vea este vídeo"^] Para ver cómo ejecutar el script de requisitos previos e interpretar los resultados.

.Lo que necesitará
* Compruebe que su sistema Linux cumple con el <<Verifique los requisitos del host,requisitos del host>>.
* Compruebe que el sistema tiene instalados los dos paquetes de software de requisitos previos (Docker Engine o Podman y Python 3).
* Asegúrese de tener privilegios de usuario raíz en el sistema Linux.


.Pasos
. Descargue el script de requisitos previos de clasificación de BlueXP desde la https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Sitio de soporte de NetApp"^]. El archivo que debe seleccionar se llama *Standalone-pre-requisito-tester-<version>*.
. Copie el archivo en el host Linux que tiene previsto utilizar (mediante `scp` o algún otro método).
. Asigne permisos para ejecutar el script.
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. Ejecute el script con el siguiente comando.
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
Agregue la opción "--darksite" sólo si está ejecutando la secuencia de comandos en un host que no tiene acceso a Internet. Algunas pruebas de requisitos previos se omiten cuando el host no está conectado a Internet.

. El script solicita la dirección IP del equipo host de clasificación de BlueXP.
+
** Introduzca la dirección IP o el nombre de host.


. La secuencia de comandos le indica si tiene un conector BlueXP instalado.
+
** Introduzca *N* si no tiene un conector instalado.
** Introduzca *y* si tiene un conector instalado. A continuación, introduzca la dirección IP o el nombre de host del conector BlueXP para que la secuencia de comandos de prueba pueda probar esta conectividad.


. La secuencia de comandos ejecuta una variedad de pruebas en el sistema y muestra los resultados a medida que avanza. Cuando termine, escribe un registro de la sesión en un archivo llamado `prerequisites-test-<timestamp>.log` en el directorio `/opt/netapp/install_logs`.


.Resultado
Si todas las pruebas de requisitos previos se ejecutaron correctamente, puede instalar la clasificación de BlueXP en el host cuando esté listo.

Si se detectan problemas, se clasifican como "recomendado" o "requerido" para ser solucionados. Los problemas recomendados normalmente son elementos que hacían que las tareas de análisis y categorización de la clasificación de BlueXP se ejecutaran más lentamente. No es necesario corregir estos elementos, pero es posible que desee abordarlos.

Si tiene algún problema "requerido", debe solucionar los problemas y volver a ejecutar el script de prueba de requisitos previos.
