---
sidebar: sidebar 
permalink: task-add-group-id-as-open.html 
keywords: permissions, open to organization, file access 
summary: 'Cuando los ID de grupo se adjuntan a archivos o carpetas en recursos compartidos de archivos NFS, definen los permisos para el archivo o la carpeta; por ejemplo, si están abiertos a la organización. Si algunos identificadores de grupo (GID) no se configuran inicialmente con el nivel de permiso «Abrir para organización», puede agregar ese permiso al GID para que todos los archivos y carpetas que tengan ese GID adjunto se consideren «abiertos a la organización».' 
---
= Defina IDs de grupo adicionales como abiertos para la organización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se adjuntan ID de grupo (GID) a archivos o carpetas en recursos compartidos de archivos NFS, definen los permisos para el archivo o la carpeta; por ejemplo, si están «abiertos a la organización». Si algunos identificadores de grupo (GID) no se configuran inicialmente con el nivel de permiso «Abrir para organización», puede agregar ese permiso al GID para que todos los archivos y carpetas que tengan ese GID adjunto se consideren «abiertos a la organización».

Después de realizar este cambio y la clasificación de BlueXP vuelve a analizar los archivos y carpetas, todos los archivos y carpetas que tengan estos ID de grupo adjuntos mostrarán este permiso en la página Detalles de la investigación, y también aparecerán en los informes donde se muestran los permisos de archivo.

Para activar esta funcionalidad, debes iniciar sesión en el sistema de clasificación de BlueXP para poder editar un archivo de configuración y ejecutar un script. Descubra cómo link:reference-log-in-to-instance.html["Inicia sesión en el sistema de clasificación de BlueXP"] Dependiendo de si instaló manualmente el software en una máquina Linux o si implementó la instancia en la nube.



== Agregue el permiso de apertura a la organización a los ID de grupo

Debe tener los Núm.s de ID de grupo (GID) antes de iniciar esta tarea.

.Pasos
. En el sistema de clasificación de BlueXP, vaya a «/opt/netapp/config/custom_configuration» y abra el archivo `data_provider.yaml`.
. En la línea ORGANIZATION_GROUP_ids: [], agregue los IDs de grupo. Por ejemplo:
+
 organization_group_ids: [1014, 1015, 21, 2021, 1013, 2020, 1018, 1019]
+
No cambie nada más en este archivo.

. Guarde los cambios en el archivo.
. Vaya a «/opt/netapp/Datasense/tools/customer_configuration/data_providers» y ejecute el siguiente script:
+
 update_data_providers_from_config_file.sh
+
Este comando confirma los permisos de ID de grupo revisados en el motor de clasificación.



.Resultado
Todos los escaneos posteriores de sus datos identificarán archivos o carpetas que tienen estos ID de grupo adjuntos como “abiertos a la organización”.

Puede editar la lista de ID de grupo y eliminar cualquier ID de grupo que haya agregado en el pasado mediante estos mismos pasos. La lista revisada de ID de grupo se actualizará después de ejecutar el script para confirmar los cambios.



== Ver la lista actual de ID de grupo

Es posible para el contenido del `data_provider.yaml` archivo de configuración que difiere de lo que realmente se ha confirmado después de ejecutar el `update_data_providers_from_config_file.sh` guión. Para ver la lista actual de ID de grupo que ha añadido a la clasificación de BlueXP, ejecute el siguiente comando en «/opt/netapp/Datasense/tools/customer_configuration/data_providers»:

 get_data_providers_configuration.sh