---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Descubre las novedades en la clasificación de BlueXP. 
---
= Novedades de la clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades en la clasificación de BlueXP.



== 5 de septiembre (versión 1,25)



=== Aplique etiquetas a un máximo de 100.000 elementos desde la página de resultados de la investigación

En el pasado, sólo se podían aplicar etiquetas a una sola página a la vez en la página de resultados de la investigación (20 elementos). Ahora puede seleccionar *todos* elementos en las páginas de resultados de la investigación y aplicar etiquetas a todos los elementos - hasta 100.000 elementos a la vez.  https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assigning-tags-to-files["Descubra cómo"].



=== Identifique archivos duplicados con un tamaño de archivo mínimo de 1 MB

Clasificación de BlueXP utilizada para identificar los archivos duplicados solo cuando los archivos tenían 50 MB o más. Ahora se pueden identificar los archivos duplicados que comienzan con 1 MB. Puedes usar los filtros de página de investigación “Tamaño de archivo” junto con “Duplicados” para ver qué archivos de un determinado tamaño están duplicados en tu entorno.



== 17 de julio de 2023 (versión 1,24)



=== Dos nuevos tipos de datos personales alemanes se identifican por la clasificación de BlueXP

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan los siguientes tipos de datos:

* Identificación alemana (Personalausweisnummer)
* Número de Seguro Social Alemán (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].



=== Rocky Linux 9 ahora es una distribución Linux compatible en la que puedes instalar la clasificación de BlueXP

Rocky Linux 9 (9,0, 9,1 y 9,2) se ha calificado como un sistema operativo compatible para la clasificación de BlueXP. Puede instalar la clasificación de BlueXP en un host Rocky Linux de su red o en un host Linux en el cloud cuando utilice la versión 1,24 del instalador. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Descubre cómo instalar la clasificación de BlueXP en un host con Rocky Linux instalado"].



=== La clasificación de BlueXP es totalmente compatible con el modo restringido y el modo privado

La clasificación de BlueXP ahora es totalmente compatible en sitios sin acceso a Internet (modo privado) y con acceso a Internet saliente limitado (modo restringido). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtén más información sobre los modos de puesta en marcha de BlueXP para Connector"^].



=== Capacidad de omitir versiones al actualizar una instalación en modo privado de la clasificación de BlueXP

Ahora puedes actualizar a una versión más reciente de la clasificación de BlueXP incluso si no es secuencial. Esto significa que ya no es necesaria la limitación actual para actualizar la clasificación de BlueXP de una versión a la vez. Esta función es relevante a partir de la versión 1,24 en adelante.



=== La API de clasificación de BlueXP ya está disponible

La API de clasificación de BlueXP permite realizar acciones, crear consultas y exportar información sobre los datos que está escaneando. La documentación interactiva se encuentra disponible mediante Swagger. La documentación se divide en varias categorías, incluidas Investigación, Cumplimiento, Gobernanza y Configuración. Cada categoría es una referencia a las pestañas de la interfaz de usuario de clasificación de BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["Obtén más información sobre las API de clasificación de BlueXP"].



== 6 de junio de 2023 (versión 1,23)



=== Ahora se admite el japonés al buscar nombres de sujetos de datos

Ahora se pueden introducir nombres en japonés al buscar el nombre de un sujeto en respuesta a una solicitud de acceso a los datos del interesado (DSAR). Puede generar un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["Informe de solicitud de acceso de asunto de datos"] con la información resultante. También puede introducir nombres japoneses en la https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["Filtro de sujeto de datos en la página Investigación de datos"] para identificar los archivos que contienen el nombre del sujeto.



=== Ubuntu ahora es una distribución Linux compatible en la que puedes instalar la clasificación de BlueXP

Ubuntu 22,04 ha sido calificado como un sistema operativo compatible para la clasificación BlueXP. Puede instalar la clasificación de BlueXP en un host Ubuntu Linux de su red o en un host Linux en el cloud cuando utilice la versión 1,23 del instalador. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Descubre cómo instalar la clasificación de BlueXP en un host con Ubuntu instalado"].



=== Red Hat Enterprise Linux 8,6 y 8,7 ya no son compatibles con las nuevas instalaciones de clasificación de BlueXP

Estas versiones no son compatibles con nuevas implementaciones porque Red Hat ya no es compatible con Docker, lo cual es un requisito previo. Si ya tienes un equipo de clasificación de BlueXP en RHEL 8,6 o 8,7, NetApp seguirá admitiendo tu configuración.



=== La clasificación de BlueXP se puede configurar como un recopilador de FPolicy para recibir eventos de FPolicy de sistemas ONTAP

Es posible habilitar los registros de auditoría de acceso a archivos para que se recopilen en el sistema de clasificación de BlueXP para los eventos de acceso a archivos detectados en volúmenes en tus entornos de trabajo. La clasificación de BlueXP puede capturar los siguientes tipos de eventos de FPolicy y los usuarios que realizaron las acciones en sus archivos: Crear, leer, escribir, eliminar, cambiar el nombre, Cambie el propietario/permisos y cambie SACL/DACL. https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["Vea cómo supervisar y gestionar eventos de acceso a archivos"].



=== Las licencias BYOL de Data Sense son ahora compatibles en sitios oscuros

Ahora puedes cargar la licencia BYOL de Data Sense en la cartera digital de BlueXP en un sitio oscuro para que se te notifique cuando tu licencia esté baja. https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["Vea cómo obtener y cargar su licencia BYOL de Data Sense"].



== 3 de abril de 2023 (versión 1.22)



=== Nuevo informe de evaluación de detección de datos

El informe de evaluación de detección de datos proporciona un análisis de alto nivel del entorno escaneado para resaltar los resultados obtenidos por el sistema y mostrar las áreas de preocupación y los posibles pasos para solucionarlos. El objetivo de este informe es dar a conocer las preocupaciones sobre la gobernanza de datos, las amenazas a la seguridad de los datos y los vacíos de cumplimiento de normativas en relación con los datos de su conjunto de datos. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["Descubra cómo generar y utilizar el Informe de evaluación de detección de datos"].



=== Capacidad de poner en marcha la clasificación de BlueXP en instancias más pequeñas en el cloud

Al implementar la clasificación de BlueXP desde un conector BlueXP en un entorno AWS, ahora puedes elegir entre dos tipos de instancia menores de los que hay disponibles con la instancia predeterminada. Si está analizando un entorno pequeño, esto puede ayudarle a ahorrar costes en la nube. Sin embargo, hay algunas restricciones al utilizar la instancia más pequeña. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Vea los tipos de instancia y las limitaciones disponibles"].



=== El script independiente ya está disponible para calificar tu sistema Linux antes de instalar la clasificación de BlueXP

Si desea verificar que su sistema Linux cumpla todos los requisitos previos independientemente de ejecutar la instalación de la clasificación de BlueXP, hay un script independiente que puede descargar y que solo prueba los requisitos previos. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Descubre cómo comprobar si tu host Linux está listo para instalar la clasificación de BlueXP"].



== 7 de marzo de 2023 (versión 1.21)



=== Nueva funcionalidad para añadir tus propias categorías personalizadas desde la interfaz de usuario de clasificación de BlueXP

Ahora, la clasificación de BlueXP te permite añadir tus propias categorías personalizadas de forma que la clasificación de BlueXP identifique los archivos que se adaptan a esas categorías. La clasificación de BlueXP tiene muchas https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["categorías predefinidas"], por lo tanto, esta característica permite agregar categorías personalizadas para identificar dónde se encuentra la información que es única para la organización en los datos.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["Leer más"^].



=== Ahora puedes añadir palabras clave personalizadas desde la interfaz de usuario de clasificación de BlueXP

La clasificación de BlueXP ha tenido la capacidad de añadir palabras clave personalizadas que la clasificación de BlueXP identificará en futuros análisis durante algún tiempo. Sin embargo, tienes que iniciar sesión en el host Linux de clasificación BlueXP y utilizar una interfaz de línea de comandos para añadir las palabras clave. En esta versión, la capacidad de añadir palabras clave personalizadas se encuentra en la interfaz de usuario de clasificación de BlueXP, por lo que es muy fácil añadir y editar estas palabras clave.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Obtén más información sobre cómo añadir palabras clave personalizadas en la interfaz de usuario de clasificación de BlueXP"^].



=== Posibilidad de que la clasificación de BlueXP *no* escanee los archivos cuando se cambie la “última hora de acceso”

De forma predeterminada, si la clasificación de BlueXP no tiene permisos de «escritura» adecuados, el sistema no analizará los archivos de tus volúmenes, porque la clasificación de BlueXP no puede revertir la «última hora de acceso» a la marca de tiempo original. Sin embargo, si no le importa si la última hora de acceso se restablece a la hora original de sus archivos, puede anular este comportamiento en la página Configuration para que la clasificación de BlueXP analice los volúmenes con independencia de los permisos.

Junto con esta funcionalidad, se ha añadido un nuevo filtro llamado «Scan Analysis Event» para que puedas ver los archivos que no se clasificaron porque la clasificación de BlueXP no pudo revertir el último acceso o los archivos clasificados aunque la clasificación de BlueXP no pudo revertir el último acceso.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["Obtén más información sobre la «marca de tiempo de último acceso» y los permisos que requiere la clasificación de BlueXP"].



=== Existen tres nuevos tipos de datos personales identificados por la clasificación de BlueXP

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan los siguientes tipos de datos:

* Número de tarjeta de identidad de Botswana (Omang)
* Número de pasaporte de Botswana
* Tarjeta de identidad de registro nacional de Singapur (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].



=== Funcionalidad actualizada para directorios

* La opción "Informe CSV claro" para Informes de investigación de datos ahora incluye información de los directorios.
* El filtro de tiempo "último acceso" muestra ahora la última hora a la que se accedió tanto para archivos como para directorios.




=== Mejoras en la instalación

* El instalador de clasificación de BlueXP para sitios sin acceso a Internet (sitios oscuros) ahora realiza una comprobación previa para asegurarse de que se cumplen los requisitos de red y del sistema para que la instalación se realice correctamente.
* Los archivos de registro de auditoría de la instalación se guardan ahora y se escriben en `/ops/netapp/install_logs`.




== 5 de febrero de 2023 (versión 1.20)



=== Posibilidad de enviar correos electrónicos de notificación basados en políticas a cualquier dirección de correo electrónico

En versiones anteriores de la clasificación de BlueXP, puedes enviar alertas por correo electrónico a los usuarios de BlueXP en tu cuenta cuando ciertas Políticas críticas devuelvan resultados. Esta función le permite obtener notificaciones para proteger sus datos cuando no está en línea. Ahora también puede enviar alertas de correo electrónico desde Directivas a cualquier otro usuario - hasta 20 direcciones de correo electrónico - que no se encuentren en su cuenta de BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["Obtenga más información sobre el envío de alertas por correo electrónico basadas en los resultados de la directiva"].



=== Ahora puedes añadir patrones personales desde la interfaz de usuario de clasificación de BlueXP

La clasificación de BlueXP ha tenido la capacidad de añadir «datos personales» personalizados que la clasificación de BlueXP identificará en futuros análisis durante algún tiempo. Sin embargo, tenía que iniciar sesión en el host Linux de clasificación de BlueXP y utilizar una línea de comandos para añadir los patrones personalizados. En esta versión, la capacidad de añadir patrones personales con un regex se encuentra en la interfaz de usuario de clasificación de BlueXP, lo que facilita la adición y edición de estos patrones personalizados.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Obtén más información sobre cómo añadir patrones personalizados en la interfaz de usuario de clasificación de BlueXP"^].



=== Capacidad para mover 15 millones de archivos con la clasificación de BlueXP

Anteriormente, la clasificación de BlueXP podía mover un máximo de 100.000 archivos de origen a cualquier recurso compartido NFS. Ahora puede mover hasta 15 millones de archivos a la vez. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Más información sobre mover archivos de origen con la clasificación de BlueXP"].



=== Capacidad para ver el número de usuarios que tienen acceso a archivos de SharePoint Online

El filtro "número de usuarios con acceso" ahora admite archivos almacenados en repositorios en línea de SharePoint. Anteriormente, solo se admitía los ficheros con recursos compartidos CIFS. Tenga en cuenta que los grupos de SharePoint que no están basados en directorios activos no se contarán en este filtro en este momento.



=== Se ha agregado un nuevo estado "éxito parcial" al panel Estado de acción

El nuevo estado «Correcto parcial» indica que una acción de clasificación de BlueXP ha finalizado y que algunos elementos han fallado y algunos elementos se han realizado correctamente, por ejemplo, cuando mueve o elimina archivos 100. Además, se ha cambiado el nombre del estado "terminado" por "correcto". En el pasado, el estado "terminado" podría incluir acciones que se han realizado correctamente y que han fallado. Ahora el estado "éxito" significa que todas las acciones se han realizado correctamente en todos los elementos. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Consulte cómo ver el panel Estado de acciones"].



== 9 de enero de 2023 (versión 1.19)



=== Capacidad para ver un gráfico de archivos que contienen datos confidenciales y que son excesivamente permisivos

El panel de control de gobierno ha agregado un área nueva _sensible Data y permisos amplios_ que proporciona un mapa térmico de archivos que contienen datos confidenciales (incluidos datos personales confidenciales y confidenciales) y que son demasiado permisivos. Esto puede ayudarle a ver dónde puede tener algunos riesgos con datos confidenciales. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Leer más"].



=== Hay tres filtros nuevos disponibles en la página Investigación de datos

Hay nuevos filtros disponibles para refinar los resultados que se muestran en la página Investigación de datos:

* El filtro "número de usuarios con acceso" muestra qué archivos y carpetas están abiertos a un determinado número de usuarios. Puede elegir un intervalo de números para refinar los resultados, por ejemplo, para ver los archivos a los que pueden acceder 51-100 usuarios.
* Los filtros "Hora de creación", "Hora descubierta", "última modificación" y "último acceso" ahora permiten crear un intervalo de fechas personalizado en lugar de sólo seleccionar un intervalo de días predefinido. Por ejemplo, puede buscar archivos con una "hora creada" "más de 6 meses" o con una fecha "última modificación" dentro de los "últimos 10 días".
* El filtro "Ruta de acceso" le permite especificar rutas que desea excluir de los resultados de la consulta filtrada. Si introduce rutas para incluir y excluir determinados datos, primero la clasificación de BlueXP busca todos los archivos en las rutas incluidas, luego quita los archivos de las rutas excluidas y, a continuación, muestra los resultados.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"].



=== La clasificación de BlueXP puede identificar el número individual japonés

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan el número individual japonés (también conocido como My Number). Esto incluye tanto el número personal como el número de mi corporativo. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].



== 11 de diciembre de 2022 (versión 1.18)



=== Mejoras en la instalación en las instalaciones

Se han agregado las siguientes mejoras para la instalación de detección de datos en las instalaciones:

* Ahora se comprueban algunos requisitos previos adicionales antes de que la instalación comience en un host local. Esto ayuda a asegurarse de que el sistema host esté preparado al 100 % para tener instalado el software Data Sense:
+
** comprobar si hay suficiente espacio en `/var/lib/docker`, `/tmp`, y. `/opt`
** pruebe los permisos pertinentes en todas las carpetas necesarias


* En la página Configuración, la sección entornos de trabajo muestra ahora _Working Environment ID_ y el _Scanner Group_ name. Necesitará conocer el identificador de entorno de trabajo si planea utilizar varios hosts de detección de datos para proporcionar potencia de procesamiento adicional para analizar sus fuentes de datos.
* También en la página Configuración, una nueva sección muestra los grupos de escáner que ha configurado y los nodos de escáner de cada grupo.


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Obtenga más información acerca de la instalación de Data Sense en un solo servidor host y en varios hosts"].



== 13 de noviembre de 2022 (versión 1.17)



=== Compatibilidad para analizar cuentas en las instalaciones de SharePoint

Ahora, el sentido de los datos puede analizar tanto cuentas en línea de SharePoint como cuentas en las instalaciones de SharePoint (SharePoint Server). Si necesita instalar SharePoint en sus propios servidores, o en sitios sin acceso a Internet, ahora puede hacer que Data Sense analice los archivos de usuario en esas cuentas. https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["Leer más"^].



=== Capacidad para volver a analizar varios directorios (carpetas o recursos compartidos)

Ahora puede volver a analizar varios directorios (carpetas o recursos compartidos) inmediatamente para que los cambios se reflejen en el sistema. Esto le permite priorizar el reexamen de determinados datos antes de otros. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Consulte cómo volver a analizar un directorio"^].



=== Posibilidad de añadir nodos de "escáner" locales adicionales para analizar orígenes de datos específicos

Si ha instalado Data Sense en una ubicación local y necesita más potencia de procesamiento de análisis para analizar determinados orígenes de datos, puede añadir más nodos de "escáner" y asignarles datos de origen. Puede añadir los nodos del escáner inmediatamente después de instalar el nodo Manager, o bien puede añadir un nodo de escáner más adelante.

Si es necesario, los nodos de escáner pueden instalarse en sistemas host que estén físicamente más cerca de los orígenes de datos que esté analizando. Cuanto más cerca esté el nodo del escáner de los datos, mejor será porque reduce la latencia de red tanto como sea posible mientras escanea datos. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["Consulte cómo instalar nodos de escáner para analizar orígenes de datos adicionales"^].



=== Los instaladores en las instalaciones ahora realizan una comprobación previa antes de iniciar la instalación

Al instalar Data Sense en un sistema Linux, el instalador comprueba si el sistema cumple todos los requisitos necesarios (CPU, RAM, capacidad, red, etc.) antes de iniciar la instalación real. Esto ayuda a detectar problemas *antes* usted pasa tiempo en la instalación.



== 6 de septiembre de 2022 (versión 1.16)



=== Capacidad de volver a analizar un repositorio inmediatamente para reflejar cambios en los archivos

Si necesita volver a analizar un repositorio determinado de inmediato para que los cambios se reflejen en el sistema, puede seleccionar el repositorio y volver a analizar dicho repositorio. Esto le permite priorizar el reexamen de determinados datos antes de otros. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Consulte cómo volver a analizar un directorio"^].



=== Nuevo filtro para el estado del análisis de detección de datos en la página Investigación de datos

El filtro “Analysis Status” (Estado del análisis) permite enumerar los archivos que se encuentran en una etapa específica del análisis de detección de datos. Puede seleccionar una opción para mostrar la lista de archivos que están *primer escaneo pendiente*, *completado*, *Rescan pendiente* o que *ha fallado* para ser escaneados.

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"^].



=== Los sujetos de datos se consideran ahora parte de los "datos personales" encontrados en los escaneos

Data Sense ahora reconoce a los sujetos de datos como parte de los resultados personales que aparecen en el Panel de cumplimiento. Además, al realizar una búsqueda en la página de investigación, puede seleccionar "Temas de datos" en "datos personales" para ver sólo los archivos que contengan sujetos de datos.



=== Los archivos de rastro de detección de datos ahora se consideran parte de las "Categorías" que se encuentran en los análisis

El sensor de datos ahora reconoce los archivos de rastro como parte de las categorías que aparecen en la consola de cumplimiento de normativas. Son archivos que crea Data Sense al mover archivos de la ubicación de origen a un recurso compartido NFS. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Obtenga más información acerca de la forma en que se crean los archivos de rastro"^].

Además, al realizar una búsqueda en la página de investigación, puede seleccionar "Data Sense Breadmigbs" en "Category" (Categoría) para ver sólo los archivos de exploración de detección de datos.



== 7 de agosto de 2022 (versión 1.15)



=== Cinco nuevos tipos de datos personales de Nueva Zelanda se identifican por el sentido de los datos

Data Sense puede identificar y categorizar archivos que contengan los siguientes tipos de datos:

* Número de cuenta bancaria de Nueva Zelanda
* Número de Licencia de conducir de Nueva Zelanda
* Número IRD de Nueva Zelanda (ID fiscal)
* Número NHI (Índice Nacional de Salud) de Nueva Zelandia
* Número de pasaporte de Nueva Zelanda


link:reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



=== Capacidad de añadir un archivo de rastro para indicar por qué se trasladó un archivo

Si utiliza la función Data Sense para mover archivos de origen a un recurso compartido de NFS, ahora puede dejar un archivo de rastro en la ubicación del archivo movido. Un archivo de rastro ayuda a los usuarios a comprender por qué se trasladó un archivo desde su ubicación original. Para cada archivo movido, el sistema crea un archivo de rastro en la ubicación de origen llamada `<filename>-breadcrumb-<date>.txt` para mostrar la ubicación en la que se ha movido el archivo y el usuario que lo ha movido. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Leer más"^].



=== Los datos personales y los datos personales confidenciales que se encuentran en sus directorios se muestran en los resultados de la investigación

La página Investigación de datos ahora muestra los resultados de datos personales y datos personales confidenciales que se encuentran en sus directorios (carpetas y recursos compartidos). https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["Vea un ejemplo aquí"^].



=== Ver el estado de cuántos volúmenes, bloques, etc. se han clasificado correctamente

Al ver los repositorios individuales que Data Sense está analizando (volúmenes, bloques, etc.), ahora puede ver cuántos se han "asignado" y cuántos se han "clasificado". La clasificación tarda más tiempo en realizarse la identificación de IA completa en todos los datos. https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["Vea cómo ver esta información"^].



=== Ahora puede agregar patrones personalizados que detección de datos identificará en sus datos

Hay dos formas de agregar "datos personales" personalizados que el sentido de datos identificará en futuras exploraciones. Esto le permite ver la imagen completa sobre dónde residen los datos potencialmente confidenciales en todos los archivos de su organización.

* Puede agregar palabras clave personalizadas desde un archivo de texto.
* Puede agregar un patrón personal utilizando una expresión regular (regex).


Estas palabras clave y patrones se agregan a los patrones predefinidos existentes que Data Sense ya utiliza, y los resultados serán visibles en la sección patrones personales. https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Leer más"^].
