---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: Descubre las novedades en la clasificación de BlueXP. 
---
= Novedades de la clasificación de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades de la clasificación de BlueXP (Cloud Data Sense).



== 15 de mayo de 2024 (Versión 1,31)



=== La clasificación está disponible como un servicio gratuito en BlueXP

La clasificación de BlueXP ahora está disponible como funcionalidad básica en BlueXP sin coste adicional para hasta 500 TiB de datos escaneados. No se requiere licencia de clasificación ni suscripción de pago. A medida que nos centramos en la funcionalidad de clasificación de BlueXP en analizar sistemas de almacenamiento de NetApp con esta nueva versión, algunas funcionalidades heredadas solo estarán disponibles para los clientes que hayan pagado previamente por una licencia. El uso de estas funciones heredadas caducará cuando el contrato pagado alcance su fecha de finalización.

link:reference-free-paid.html["Obtenga más información sobre las características obsoletas"].



== 1 de abril de 2024 (Versión 1,30)



=== Compatibilidad añadida para la clasificación de BlueXP de RHEL v8,8 y v9,3

Esta versión es compatible con Red Hat Enterprise Linux v8,8 y v9,3, además de la versión 9.x admitida anteriormente, que requiere Podman, en lugar del motor Docker. Esto es aplicable a cualquier instalación manual en las instalaciones de la clasificación de BlueXP.

Los siguientes sistemas operativos deben utilizar el motor de contenedor Podman y requieren la versión de clasificación de BlueXP 1,30 o posterior: Red Hat Enterprise Linux versiones 8,8, 9,0, 9,1, 9,2 y 9,3.

Más información acerca de https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Información general sobre las puestas en marcha de clasificación de BlueXP"].

La clasificación BlueXP es compatible si instala el Connector en un host RHEL 8 o 9 que reside en las instalaciones. No se admite si el host RHEL 8 o 9 reside en AWS, Azure o Google Cloud.



=== Se quitó la opción para activar la recogida del registro de auditoría

Se deshabilitó la opción para activar la recogida de registros de auditoría.



=== Velocidad de escaneo mejorada

Se ha mejorado el rendimiento de escaneo en nodos de escáner secundarios. Puede agregar más nodos de escáner si necesita potencia de procesamiento adicional para sus escaneos. Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Instala la clasificación de BlueXP en un host que tenga acceso a Internet"].



=== Actualizaciones automáticas

Si implementaste la clasificación de BlueXP en un sistema con acceso a Internet, el sistema se actualizará automáticamente. Anteriormente, la actualización se produjo después de un tiempo específico transcurrido desde la última actividad del usuario. Con esta versión, la clasificación de BlueXP se actualiza automáticamente si la hora local es entre las 1:00 y las 5:00:00. Si la hora local está fuera de estas horas, la actualización se produce después de que transcurra un tiempo específico desde la última actividad del usuario. Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Instale en un host Linux con acceso a Internet"].

Si implementaste la clasificación de BlueXP sin acceso a Internet, tendrás que actualizar manualmente. Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["Instala la clasificación BlueXP en un host Linux sin acceso a Internet"].



== 4 de marzo de 2024 (versión 1,29)



=== Ahora puede excluir los datos de escaneo que residen en ciertos directorios de origen de datos

Si desea que la clasificación de BlueXP excluya los datos de análisis que residen en determinados directorios de orígenes de datos, puede añadir estos nombres de directorio a un archivo de configuración que procese la clasificación de BlueXP. Esta función le permite evitar el escaneo de directorios que no son necesarios, o que daría lugar a la devolución de resultados de datos personales falsos positivos.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["Leer más"].



=== El soporte de instancias extra grandes ya está cualificado

Si necesitas la clasificación de BlueXP para analizar más de 250 millones de archivos, puedes utilizar una instancia de Extra Large en la puesta en marcha de la nube o en la instalación on-premises. Este tipo de sistema puede escanear hasta 500 millones de archivos.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Leer más"].



== 10 de enero de 2024 (versión 1,27)



=== Los resultados de la página de investigación ahora muestran el tamaño total además del número total de elementos

Los resultados filtrados en la página de investigación ahora muestran el tamaño total de los elementos además del número total de archivos. Esto puede ayudar al mover archivos, eliminar archivos y más.



=== Configurar IDs de grupo adicionales como abiertos para la organización

Ahora puede configurar los ID de grupo en NFS para que se consideren «abiertos a la organización» directamente desde la clasificación de BlueXP si el grupo no se había establecido inicialmente con ese permiso. Todos los archivos y carpetas que tengan estos ID de grupo adjuntos se mostrarán como abiertos a la organización en la página Detalles de la investigación. Descubra cómo https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["Agregar ID de grupo adicionales como abiertos a la organización"].



== 14 de diciembre de 2023 (versión 1.26.6)

Esta versión incluye algunas mejoras menores.

La versión también eliminó las siguientes opciones:

* Se deshabilitó la opción para activar la recogida de registros de auditoría.
* Durante la investigación de directorios, la opción de calcular el número de datos de información personal identificable (PII) por directorios no está disponible. Consulte link:task-investigate-data.html#filter-data-by-sensitivity-and-content["Investigue los datos almacenados en su organización"].
* Se ha desactivado la opción de integrar datos mediante etiquetas de Azure Information Protection (AIP). Consulte link:task-org-private-data.html["Organice sus datos privados"].




== 6 de noviembre de 2023 (versión 1.26.3)



=== Los siguientes problemas se han solucionado en esta versión

* Se ha corregido una inconsistencia al presentar el número de archivos escaneados por el sistema en los paneles de control.
* Se ha mejorado el comportamiento de escaneo al manejar e informar sobre archivos y directorios con caracteres especiales en el nombre y los metadatos.




== 4 de octubre de 2023 (versión 1,26)



=== Compatibilidad con las instalaciones on-premises de la clasificación de BlueXP en la versión 9 de RHEL

Red Hat Enterprise Linux, las versiones 8 y 9 no son compatibles con el motor Docker; se requería para la instalación de la clasificación de BlueXP. Ahora admitimos la instalación de clasificación de BlueXP en RHEL 9,0, 9,1 y 9,2 mediante Podman versión 4 o posterior como infraestructura de contenedores. Si tu entorno requiere el uso de las versiones más recientes de RHEL, ahora puedes instalar la clasificación de BlueXP (versión 1,26 o posterior) cuando utilizas Podman.

En este momento, no admitimos instalaciones de sitios oscuros ni entornos de análisis distribuidos (con nodos de escáner maestro y remoto) cuando se usa RHEL 9.x.



== 5 de septiembre de 2023 (versión 1,25)



=== Implementaciones pequeñas y medianas no disponibles temporalmente

Cuando implementas una instancia de clasificación de BlueXP en AWS, la opción de seleccionar *Desplegar > Configuración* y elegir una instancia pequeña o mediana no estará disponible en este momento. Aún puede implementar la instancia utilizando el tamaño de instancia grande seleccionando *Desplegar > Desplegar*.



=== Aplique etiquetas a un máximo de 100.000 elementos desde la página de resultados de la investigación

En el pasado, sólo se podían aplicar etiquetas a una sola página a la vez en la página de resultados de la investigación (20 elementos). Ahora puede seleccionar *todos* elementos en las páginas de resultados de la investigación y aplicar etiquetas a todos los elementos - hasta 100.000 elementos a la vez. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["Descubra cómo"].



=== Identifique archivos duplicados con un tamaño de archivo mínimo de 1 MB

Clasificación de BlueXP utilizada para identificar los archivos duplicados solo cuando los archivos tenían 50 MB o más. Ahora se pueden identificar los archivos duplicados que comienzan con 1 MB. Puedes usar los filtros de página de investigación “Tamaño de archivo” junto con “Duplicados” para ver qué archivos de un determinado tamaño están duplicados en tu entorno.



== 17 de julio de 2023 (versión 1,24)



=== Dos nuevos tipos de datos personales alemanes se identifican por la clasificación de BlueXP

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan los siguientes tipos de datos:

* Identificación alemana (Personalausweisnummer)
* Número de Seguro Social Alemán (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].



=== La clasificación de BlueXP es totalmente compatible con el modo restringido y el modo privado

La clasificación de BlueXP ahora es totalmente compatible en sitios sin acceso a Internet (modo privado) y con acceso a Internet saliente limitado (modo restringido). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Obtén más información sobre los modos de puesta en marcha de BlueXP para Connector"^].



=== Capacidad de omitir versiones al actualizar una instalación en modo privado de la clasificación de BlueXP

Ahora puedes actualizar a una versión más reciente de la clasificación de BlueXP incluso si no es secuencial. Esto significa que ya no es necesaria la limitación actual para actualizar la clasificación de BlueXP de una versión a la vez. Esta función es relevante a partir de la versión 1,24 en adelante.



=== La API de clasificación de BlueXP ya está disponible

La API de clasificación de BlueXP permite realizar acciones, crear consultas y exportar información sobre los datos que está escaneando. La documentación interactiva se encuentra disponible mediante Swagger. La documentación se divide en varias categorías, incluidas Investigación, Cumplimiento, Gobernanza y Configuración. Cada categoría es una referencia a las pestañas de la interfaz de usuario de clasificación de BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["Obtén más información sobre las API de clasificación de BlueXP"].



== 6 de junio de 2023 (versión 1,23)



=== Ahora se admite el japonés al buscar nombres de sujetos de datos

Ahora se pueden introducir nombres en japonés al buscar el nombre de un sujeto en respuesta a una solicitud de acceso a los datos del interesado (DSAR). Puede generar un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["Informe de solicitud de acceso de asunto de datos"] con la información resultante. También puede introducir nombres japoneses en la https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["Filtro de sujeto de datos en la página Investigación de datos"] para identificar los archivos que contienen el nombre del sujeto.



=== Ubuntu ahora es una distribución Linux compatible en la que puedes instalar la clasificación de BlueXP

Ubuntu 22,04 ha sido calificado como un sistema operativo compatible para la clasificación BlueXP. Puede instalar la clasificación de BlueXP en un host Ubuntu Linux de su red o en un host Linux en el cloud cuando utilice la versión 1,23 del instalador. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Descubre cómo instalar la clasificación de BlueXP en un host con Ubuntu instalado"].



=== Red Hat Enterprise Linux 8,6 y 8,7 ya no son compatibles con las nuevas instalaciones de clasificación de BlueXP

Estas versiones no son compatibles con nuevas implementaciones porque Red Hat ya no es compatible con Docker, lo cual es un requisito previo. Si ya tienes un equipo de clasificación de BlueXP en RHEL 8,6 o 8,7, NetApp seguirá admitiendo tu configuración.



=== La clasificación de BlueXP se puede configurar como un recopilador de FPolicy para recibir eventos de FPolicy de sistemas ONTAP

Es posible habilitar los registros de auditoría de acceso a archivos para que se recopilen en el sistema de clasificación de BlueXP para los eventos de acceso a archivos detectados en volúmenes en tus entornos de trabajo. La clasificación de BlueXP puede capturar los siguientes tipos de eventos de FPolicy y los usuarios que realizaron las acciones en sus archivos: Crear, leer, escribir, eliminar, cambiar el nombre, Cambie el propietario/permisos y cambie SACL/DACL.



=== Las licencias BYOL de Data Sense son ahora compatibles en sitios oscuros

Ahora puedes cargar la licencia BYOL de Data Sense en la cartera digital de BlueXP en un sitio oscuro para que se te notifique cuando tu licencia esté baja. https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["Vea cómo obtener y cargar su licencia BYOL de Data Sense"].



== 3 de abril de 2023 (versión 1.22)



=== Nuevo informe de evaluación de detección de datos

El informe de evaluación de detección de datos proporciona un análisis de alto nivel del entorno escaneado para resaltar los resultados obtenidos por el sistema y mostrar las áreas de preocupación y los posibles pasos para solucionarlos. El objetivo de este informe es dar a conocer las preocupaciones sobre la gobernanza de datos, las amenazas a la seguridad de los datos y los vacíos de cumplimiento de normativas en relación con los datos de su conjunto de datos. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["Descubra cómo generar y utilizar el Informe de evaluación de detección de datos"].



=== Capacidad de poner en marcha la clasificación de BlueXP en instancias más pequeñas en el cloud

Al implementar la clasificación de BlueXP desde un conector BlueXP en un entorno AWS, ahora puedes elegir entre dos tipos de instancia menores de los que hay disponibles con la instancia predeterminada. Si está analizando un entorno pequeño, esto puede ayudarle a ahorrar costes en la nube. Sin embargo, hay algunas restricciones al utilizar la instancia más pequeña. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Vea los tipos de instancia y las limitaciones disponibles"].



=== El script independiente ya está disponible para calificar tu sistema Linux antes de instalar la clasificación de BlueXP

Si desea verificar que su sistema Linux cumpla todos los requisitos previos independientemente de ejecutar la instalación de la clasificación de BlueXP, hay un script independiente que puede descargar y que solo prueba los requisitos previos. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Descubre cómo comprobar si tu host Linux está listo para instalar la clasificación de BlueXP"].



== 7 de marzo de 2023 (versión 1.21)



=== Nueva funcionalidad para añadir tus propias categorías personalizadas desde la interfaz de usuario de clasificación de BlueXP

Ahora, la clasificación de BlueXP te permite añadir tus propias categorías personalizadas de forma que la clasificación de BlueXP identifique los archivos que se adaptan a esas categorías. La clasificación de BlueXP tiene muchas https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["categorías predefinidas"], por lo tanto, esta característica permite agregar categorías personalizadas para identificar dónde se encuentra la información que es única para la organización en los datos.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["Leer más"^].



=== Ahora puedes añadir palabras clave personalizadas desde la interfaz de usuario de clasificación de BlueXP

La clasificación de BlueXP ha tenido la capacidad de añadir palabras clave personalizadas que la clasificación de BlueXP identificará en futuros análisis durante algún tiempo. Sin embargo, tienes que iniciar sesión en el host Linux de clasificación BlueXP y utilizar una interfaz de línea de comandos para añadir las palabras clave. En esta versión, la capacidad de añadir palabras clave personalizadas se encuentra en la interfaz de usuario de clasificación de BlueXP, por lo que es muy fácil añadir y editar estas palabras clave.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Obtén más información sobre cómo añadir palabras clave personalizadas en la interfaz de usuario de clasificación de BlueXP"^].



=== Posibilidad de que la clasificación de BlueXP *no* escanee los archivos cuando se cambie la “última hora de acceso”

De forma predeterminada, si la clasificación de BlueXP no tiene permisos de «escritura» adecuados, el sistema no analizará los archivos de tus volúmenes, porque la clasificación de BlueXP no puede revertir la «última hora de acceso» a la marca de tiempo original. Sin embargo, si no le importa si la última hora de acceso se restablece a la hora original de sus archivos, puede anular este comportamiento en la página Configuration para que la clasificación de BlueXP analice los volúmenes con independencia de los permisos.

Junto con esta funcionalidad, se ha añadido un nuevo filtro llamado «Scan Analysis Event» para que puedas ver los archivos que no se clasificaron porque la clasificación de BlueXP no pudo revertir el último acceso o los archivos clasificados aunque la clasificación de BlueXP no pudo revertir el último acceso.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["Obtén más información sobre la «marca de tiempo de último acceso» y los permisos que requiere la clasificación de BlueXP"].



=== Existen tres nuevos tipos de datos personales identificados por la clasificación de BlueXP

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan los siguientes tipos de datos:

* Número de tarjeta de identidad de Botswana (Omang)
* Número de pasaporte de Botswana
* Tarjeta de identidad de registro nacional de Singapur (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].



=== Funcionalidad actualizada para directorios

* La opción "Informe CSV claro" para Informes de investigación de datos ahora incluye información de los directorios.
* El filtro de tiempo "último acceso" muestra ahora la última hora a la que se accedió tanto para archivos como para directorios.




=== Mejoras en la instalación

* El instalador de clasificación de BlueXP para sitios sin acceso a Internet (sitios oscuros) ahora realiza una comprobación previa para asegurarse de que se cumplen los requisitos de red y del sistema para que la instalación se realice correctamente.
* Los archivos de registro de auditoría de la instalación se guardan ahora y se escriben en `/ops/netapp/install_logs`.




== 5 de febrero de 2023 (versión 1.20)



=== Posibilidad de enviar correos electrónicos de notificación basados en políticas a cualquier dirección de correo electrónico

En versiones anteriores de la clasificación de BlueXP, puedes enviar alertas por correo electrónico a los usuarios de BlueXP en tu cuenta cuando ciertas Políticas críticas devuelvan resultados. Esta función le permite obtener notificaciones para proteger sus datos cuando no está en línea. Ahora también puede enviar alertas de correo electrónico desde Directivas a cualquier otro usuario - hasta 20 direcciones de correo electrónico - que no se encuentren en su cuenta de BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#send-email-alerts-when-non-compliant-data-is-found["Obtenga más información sobre el envío de alertas por correo electrónico basadas en los resultados de la directiva"].



=== Ahora puedes añadir patrones personales desde la interfaz de usuario de clasificación de BlueXP

La clasificación de BlueXP ha tenido la capacidad de añadir «datos personales» personalizados que la clasificación de BlueXP identificará en futuros análisis durante algún tiempo. Sin embargo, tenía que iniciar sesión en el host Linux de clasificación de BlueXP y utilizar una línea de comandos para añadir los patrones personalizados. En esta versión, la capacidad de añadir patrones personales con un regex se encuentra en la interfaz de usuario de clasificación de BlueXP, lo que facilita la adición y edición de estos patrones personalizados.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Obtén más información sobre cómo añadir patrones personalizados en la interfaz de usuario de clasificación de BlueXP"^].



=== Capacidad para mover 15 millones de archivos con la clasificación de BlueXP

Anteriormente, la clasificación de BlueXP podía mover un máximo de 100.000 archivos de origen a cualquier recurso compartido NFS. Ahora puede mover hasta 15 millones de archivos a la vez. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#move-source-files-to-an-nfs-share["Más información sobre mover archivos de origen con la clasificación de BlueXP"].



=== Capacidad para ver el número de usuarios que tienen acceso a archivos de SharePoint Online

El filtro "número de usuarios con acceso" ahora admite archivos almacenados en repositorios en línea de SharePoint. Anteriormente, solo se admitía los ficheros con recursos compartidos CIFS. Tenga en cuenta que los grupos de SharePoint que no están basados en directorios activos no se contarán en este filtro en este momento.



=== Se ha agregado un nuevo estado "éxito parcial" al panel Estado de acción

El nuevo estado «Correcto parcial» indica que una acción de clasificación de BlueXP ha finalizado y que algunos elementos han fallado y algunos elementos se han realizado correctamente, por ejemplo, cuando mueve o elimina archivos 100. Además, se ha cambiado el nombre del estado "terminado" por "correcto". En el pasado, el estado "terminado" podría incluir acciones que se han realizado correctamente y que han fallado. Ahora el estado "éxito" significa que todas las acciones se han realizado correctamente en todos los elementos. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Consulte cómo ver el panel Estado de acciones"].



== 9 de enero de 2023 (versión 1.19)



=== Capacidad para ver un gráfico de archivos que contienen datos confidenciales y que son excesivamente permisivos

El panel de control de gobierno ha agregado un área nueva _sensible Data y permisos amplios_ que proporciona un mapa térmico de archivos que contienen datos confidenciales (incluidos datos personales confidenciales y confidenciales) y que son demasiado permisivos. Esto puede ayudarle a ver dónde puede tener algunos riesgos con datos confidenciales. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Leer más"].



=== Hay tres filtros nuevos disponibles en la página Investigación de datos

Hay nuevos filtros disponibles para refinar los resultados que se muestran en la página Investigación de datos:

* El filtro "número de usuarios con acceso" muestra qué archivos y carpetas están abiertos a un determinado número de usuarios. Puede elegir un intervalo de números para refinar los resultados, por ejemplo, para ver los archivos a los que pueden acceder 51-100 usuarios.
* Los filtros "Hora de creación", "Hora descubierta", "última modificación" y "último acceso" ahora permiten crear un intervalo de fechas personalizado en lugar de sólo seleccionar un intervalo de días predefinido. Por ejemplo, puede buscar archivos con una "hora creada" "más de 6 meses" o con una fecha "última modificación" dentro de los "últimos 10 días".
* El filtro "Ruta de acceso" le permite especificar rutas que desea excluir de los resultados de la consulta filtrada. Si introduce rutas para incluir y excluir determinados datos, primero la clasificación de BlueXP busca todos los archivos en las rutas incluidas, luego quita los archivos de las rutas excluidas y, a continuación, muestra los resultados.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"].



=== La clasificación de BlueXP puede identificar el número individual japonés

La clasificación de BlueXP puede identificar y categorizar los archivos que contengan el número individual japonés (también conocido como My Number). Esto incluye tanto el número personal como el número de mi corporativo. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consulta todos los tipos de datos personales que la clasificación de BlueXP puede identificar en tus datos"].
