= Versión 1,40
:allow-uri-read: 




=== Versión 1,40

Esta versión de clasificación de BlueXP  incluye las siguientes actualizaciones.

.Compatibilidad con RHEL 9,5
Esta versión es compatible con Red Hat Enterprise Linux v9,5 además de las versiones compatibles anteriormente. Esto se aplica a cualquier instalación manual en las instalaciones de la clasificación BlueXP , incluidas las puestas en marcha de sitios oscuros.

Los siguientes sistemas operativos requieren el uso del motor de contenedores Podman y requieren la versión de clasificación BlueXP  1,30 o superior: Red Hat Enterprise Linux versión 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 y 9,5.

.Priorice las adquisiciones
Al escanear la configuración, puede dar prioridad a las secuencias más importantes para que se realicen antes que otras exploraciones. Esta función ayuda cuando tiene muchos entornos de trabajo y desea asegurarse de que las exploraciones de alta prioridad se realizan correctamente al principio.

Existen dos tipos de adquisiciones:

* *Los escaneos de solo mapeo* proporcionan solo una visión general de alto nivel de sus datos. La asignación se puede realizar en sus orígenes de datos muy rápidamente porque no tiene acceso a los archivos para ver los datos dentro.
* *Map and Classify* escaneos proporcionan un escaneo de nivel profundo de sus datos.


Es posible que se beneficie del uso de escaneos de sólo asignación para escanear rápidamente los datos e identificar las fuentes de datos que requieren más investigación y, a continuación, habilitar Asignar y clasificar escaneos solo en los orígenes o volúmenes de datos necesarios.

La prioridad se asigna sólo a las secuencias de sólo asignación, no a las secuencias de asignación y clasificación.

La prioridad se establece en 1 de forma predeterminada, y puede cambiarla a cualquier número entre 1 y 10. Cuanto menor sea el número, mayor será la prioridad. Si no establece una prioridad, al escaneo se le asigna una prioridad de 5.

Para cambiar la prioridad, haga lo siguiente:

. En el menú de clasificación de BlueXP , selecciona *Configuración*.
. Seleccione los recursos que desea priorizar.
. En la opción Acciones ..., seleccione *Priorizar escaneo*.


.Reintente las exploraciones
Con esta versión, puede volver a intentar las exploraciones que hayan fallado. Esta función es útil cuando se produce un error de escaneo debido a un problema temporal, como una interrupción de la red. Puede volver a intentar la exploración sin tener que volver a configurarla.

Para volver a intentar una exploración, haga lo siguiente:

. En el menú de clasificación de BlueXP , selecciona *Configuración*.
. Debe realizar una de las siguientes acciones:
+
** Para volver a intentar todos los escaneos fallidos, seleccione *Reintentar todos los escaneos*.
** Para volver a intentar una exploración específica, seleccione el recurso y seleccione *Reintentar escaneo* en la opción Acciones...




La adquisición se vuelve a intentar con la misma configuración que la adquisición original. Si el escaneo vuelve a fallar, puede volver a intentarlo tantas veces como sea necesario.
