= Versión 1,42
:allow-uri-read: 




=== Versión 1,42

Esta versión de clasificación de BlueXP  incluye:

.Análisis masivo para entornos de trabajo
La clasificación BlueXP  admite operaciones masivas para entornos de trabajo. Puede optar por activar la asignación de exploraciones, activar la asignación y clasificación de exploraciones, desactivar exploraciones o crear una configuración personalizada en los volúmenes del entorno de trabajo. Si se realiza una selección para un volumen individual, se anula la selección masiva. Para realizar una operación masiva, navegue a la página **Configuración** y realice su selección.

.Descargue el informe de investigación localmente
La clasificación BlueXP  permite descargar informes de investigación de datos localmente para verlos en el explorador. Si selecciona la opción local, la investigación de datos solo está disponible en formato CSV y solo muestra las primeras 10.000 filas de datos.

Para obtener más información, consulte link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Investiga los datos almacenados en tu organización con la clasificación BlueXP "].
