= Versión 1,39
:allow-uri-read: 




=== Versión 1,39

Esta versión de clasificación de BlueXP  actualiza el proceso de exportación del informe de investigación de datos. Esta actualización de exportación es útil para realizar análisis adicionales de sus datos, crear visualizaciones adicionales de los datos o compartir los resultados de su investigación de datos con otros.

Anteriormente, la exportación del informe de investigación de datos se limitaba a 10.000 filas. Con esta versión, el límite se ha eliminado para que pueda exportar todos sus datos. Este cambio le permite exportar más datos de sus informes de investigación de datos, lo que le proporciona más flexibilidad en el análisis de datos.

Puede elegir el entorno de trabajo, los volúmenes, la carpeta de destino y el formato JSON o CSV. El nombre de archivo exportado incluye una marca de tiempo para ayudarle a identificar cuándo se exportaron los datos.

Los entornos de trabajo compatibles incluyen:

* Cloud Volumes ONTAP
* FSX para ONTAP
* ONTAP
* Compartir grupo


La exportación de datos del informe de investigación de datos tiene las siguientes limitaciones:

* El número máximo de registros para descargar es de 500 millones por tipo (archivos, directorios y tablas)
* Se espera que un millón de registros tarde unos 35 minutos en exportarse.


Para obtener más información sobre la investigación de datos y el informe, consulte https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investiga los datos almacenados en tu organización"].
