= Versión 1,45
:allow-uri-read: 




=== Versión 1,45

Esta versión de BlueXP classification incluye cambios de código que optimizan la utilización de recursos y:

.Flujo de trabajo mejorado para agregar recursos compartidos de archivos para escanear
Se ha simplificado el flujo de trabajo para agregar recursos compartidos de archivos a un grupo. El proceso también diferencia la compatibilidad con el protocolo CIFS según el tipo de autenticación (Kerberos o NTLM).

Para obtener más información, consulte xref:task-scanning-file-shares.html[Analizar recursos compartidos de archivos].

.Información mejorada del propietario del archivo
Ahora puede ver más información sobre los propietarios de los archivos capturados en la pestaña Investigación. Al visualizar los metadatos de un archivo en la pestaña Investigación, localice al propietario del archivo y seleccione **Ver detalles** para ver el nombre de usuario, el correo electrónico y el nombre de la cuenta SAM. También puede ver otros elementos propiedad de este usuario. Esta función solo está disponible para entornos de trabajo con Active Directory.

Para obtener más información, consulte xref:task-investigate-data.html[Investigue los datos almacenados en su organización].
